import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}});
async function context(req:Request){const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,auth=req.headers.get('Authorization')||'';const userClient=createClient(url,anon,{global:{headers:{Authorization:auth}}});const {data:{user},error}=await userClient.auth.getUser();if(error||!user)throw new Error('Unauthorized');return{user,admin:createClient(url,service,{auth:{persistSession:false}})}}

const weapons={garlic:{rarity:'Common'},chili:{rarity:'Common'},cabbage:{rarity:'Uncommon'},onion:{rarity:'Uncommon'},potato:{rarity:'Rare'},eggplant:{rarity:'Rare'},coconut:{rarity:'Epic'},pineapple:{rarity:'Epic'},peanut:{rarity:'Legendary'},pepper:{rarity:'Mythic'}};
const rarityOrder=['Common','Uncommon','Rare','Epic','Legendary','Mythic'];
function rollRarity(state:any){if(state.since_mythic>=199)return'Mythic';if(state.since_legendary>=79)return'Legendary';if(state.since_epic>=29)return'Epic';if(state.since_rare>=9)return'Rare';const r=crypto.getRandomValues(new Uint32Array(1))[0]/4294967296;return r<.50?'Common':r<.75?'Uncommon':r<.88?'Rare':r<.95?'Epic':r<.99?'Legendary':'Mythic'}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const {user,admin}=await context(req),b=await req.json(),action=String(b.action||'profile');let {data:profile}=await admin.from('profiles').select('id,player_name,avatar,battle_points,selected_starter,free_starter_spin,banned,total_games,total_play_time,total_kills,best_endless_score,best_survival,highest_level,total_bosses').eq('id',user.id).maybeSingle();if(!profile)return json({error:'Create your player profile first'},404);if(profile.banned)return json({error:'Account suspended'},403);
 if(action==='profile'){const {data:inventory}=await admin.from('starter_inventory').select('weapon_id,copies,star_rank,unlocked_at').eq('user_id',user.id);const {data:gs}=await admin.from('gacha_state').select('*').eq('user_id',user.id).maybeSingle();const {data:role}=await admin.from('progression_admins').select('role').eq('user_id',user.id).maybeSingle();return json({profile,inventory:inventory||[],gacha:gs||{total_spins:0,since_rare:0,since_epic:0,since_legendary:0,since_mythic:0},adminRole:role?.role||null})}
 if(action==='spin'){let {data:state}=await admin.from('gacha_state').select('*').eq('user_id',user.id).maybeSingle();state=state||{user_id:user.id,total_spins:0,since_rare:0,since_epic:0,since_legendary:0,since_mythic:0};const free=profile.free_starter_spin;if(!free&&profile.battle_points<250)return json({error:'Not enough Battle Points'},400);const rarity=rollRarity(state),ids=Object.keys(weapons).filter(id=>weapons[id as keyof typeof weapons].rarity===rarity),weaponId=ids[crypto.getRandomValues(new Uint32Array(1))[0]%ids.length],rank=rarityOrder.indexOf(rarity);const {data:old}=await admin.from('starter_inventory').select('*').eq('user_id',user.id).eq('weapon_id',weaponId).maybeSingle();const copies=(old?.copies||0)+1,star=Math.min(5,Math.max(0,copies-1));await admin.from('starter_inventory').upsert({user_id:user.id,weapon_id:weaponId,copies,star_rank:star,updated_at:new Date().toISOString()});const next={user_id:user.id,total_spins:state.total_spins+1,since_rare:rank>=2?0:state.since_rare+1,since_epic:rank>=3?0:state.since_epic+1,since_legendary:rank>=4?0:state.since_legendary+1,since_mythic:rank>=5?0:state.since_mythic+1,updated_at:new Date().toISOString()};await admin.from('gacha_state').upsert(next);await admin.from('profiles').update({battle_points:free?profile.battle_points:profile.battle_points-250,free_starter_spin:false}).eq('id',user.id);return json({weaponId,rarity,duplicate:!!old,copies,starRank:star,battlePoints:free?profile.battle_points:profile.battle_points-250,pity:next,free})}
 if(action==='select'){const id=String(b.weaponId||'');if(!weapons[id as keyof typeof weapons])return json({error:'Invalid starter weapon'},400);const {data:owned}=await admin.from('starter_inventory').select('weapon_id').eq('user_id',user.id).eq('weapon_id',id).maybeSingle();if(!owned)return json({error:'Starter weapon is locked'},403);await admin.from('profiles').update({selected_starter:id}).eq('id',user.id);return json({selected:id})}
 if(action==='claim'){const type=String(b.type||''),key=String(b.claimKey||'').slice(0,100);if(!key)return json({error:'Invalid reward'},400);let amount=0;if(type==='quiz')amount=5;else if(type==='run')amount=Math.min(300,30+Math.floor(Number(b.survival||0)/60)*4+Math.floor(Number(b.bosses||0))*25);else if(type==='achievement')amount=50;else if(type==='daily')amount=75;else if(type==='weekly')amount=300;else return json({error:'Unknown reward'},400);const {error:claimError}=await admin.from('bp_reward_claims').insert({user_id:user.id,claim_key:key,event_type:type,bp_awarded:amount});if(claimError)return json({error:'Reward already claimed'},409);const bp=profile.battle_points+amount;await admin.from('profiles').update({battle_points:bp}).eq('id',user.id);return json({awarded:amount,battlePoints:bp})}
 return json({error:'Unknown action'},400)}catch(e){return json({error:e.message||'Gacha request failed'},e.message==='Unauthorized'?401:400)}});
