/* Nutrition Quest — native Supabase Realtime co-op client.
   No npm or third-party browser library is used. The native WebSocket client
   speaks Supabase's Phoenix-channel protocol and sends compact broadcasts. */
'use strict';
const MP={
 active:false,inRoom:false,isHost:false,room:null,roomCode:'',socket:null,joined:false,players:new Map(),remotePlayers:new Map(),enemyTargets:new Map(),ref:0,heartbeat:null,sendClock:0,snapshotClock:0,roomClock:20,memberClock:15,ping:0,lastPingAt:0,reconnectTimer:null,reconnectUntil:0,colors:['#57e089','#62b8ff','#ff8cc8'],
 uid(){return save.onlineAuth?.user?.id||''}, nextRef(){return String(++this.ref)},
 setStatus(text,kind='connecting'){const el=document.querySelector('#mpConnection');if(el){el.textContent='● '+text;el.className='mp-connection '+kind}},
 async api(path,options={}){await Online.auth();const r=await fetch(`${Online.cfg.url}/rest/v1/${path}`,{...options,headers:{...Online.headers(),Prefer:options.prefer||'return=representation',...(options.headers||{})}});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.message||d?.hint||'Room request failed');return d},
 code(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return Array.from({length:6},()=>chars[Math.floor(Math.random()*chars.length)]).join('')},
 async createRoom(){try{this.setStatus('Creating room…');await Online.syncProfile();let result=null;for(let i=0;i<6&&!result;i++){const code=this.code();try{const rows=await this.api('multiplayer_rooms',{method:'POST',body:JSON.stringify({code,host_id:this.uid(),status:'lobby',max_players:3}),prefer:'return=representation'});result=rows[0]}catch(e){if(i===5)throw e}}this.room=result;this.roomCode=result.code;this.isHost=true;await this.joinRoomRecord();await this.connect()}catch(e){this.setStatus(e.message,'offline');toast(e.message)}},
 async joinByCode(){const code=document.querySelector('#mpRoomInput').value.trim().toUpperCase();if(code.length!==6)return toast('Enter a 6-character room code');try{this.setStatus('Joining room…');await Online.syncProfile();const rooms=await this.api(`multiplayer_rooms?code=eq.${encodeURIComponent(code)}&select=*`);if(!rooms.length)throw new Error('Room code not found');if(rooms[0].status==='closed')throw new Error('This room has been closed');const members=await this.api(`multiplayer_members?room_id=eq.${rooms[0].id}&connected=eq.true&select=player_id`),wasMember=members.some(m=>m.player_id===this.uid());if(rooms[0].status==='playing'&&!wasMember)throw new Error('Room already started. Ask the host to create a new room.');if(members.length>=3&&!wasMember)throw new Error('Room is full');this.rejoiningPlaying=rooms[0].status==='playing'&&wasMember;this.room=rooms[0];this.roomCode=code;this.isHost=rooms[0].host_id===this.uid();await this.joinRoomRecord();await this.connect()}catch(e){this.setStatus(e.message,'offline');toast(e.message)}},
 async joinRoomRecord(){await this.api('multiplayer_members',{method:'POST',body:JSON.stringify({room_id:this.room.id,player_id:this.uid(),player_name:save.profile.name,avatar:save.profile.avatar,ready:false,connected:true,last_seen:new Date().toISOString()}),prefer:'resolution=merge-duplicates,return=representation'})},
 async connect(){this.closeSocket(false);const base=Online.cfg.url.replace(/^http/,'ws');const token=await Online.auth();this.setStatus('Connecting…');this.socket=new WebSocket(`${base}/realtime/v1/websocket?apikey=${encodeURIComponent(Online.cfg.anonKey)}&vsn=1.0.0`);this.socket.onopen=()=>{const topic='realtime:room:'+this.roomCode;this.sendRaw(topic,'phx_join',{config:{broadcast:{ack:false,self:false},presence:{key:this.uid()},postgres_changes:[]},access_token:token});this.heartbeat=setInterval(()=>{this.lastPingAt=performance.now();this.sendRaw('phoenix','heartbeat',{})},15000)};this.socket.onmessage=e=>this.onMessage(JSON.parse(e.data));this.socket.onerror=()=>this.setStatus('Connection error','offline');this.socket.onclose=()=>{this.joined=false;clearInterval(this.heartbeat);if(this.inRoom&&Date.now()<this.reconnectUntil)this.reconnectTimer=setTimeout(()=>this.connect(),1600);else if(this.inRoom)this.setStatus('Disconnected','offline')}} ,
 sendRaw(topic,event,payload,ref=this.nextRef()){if(this.socket?.readyState===1)this.socket.send(JSON.stringify({topic,event,payload,ref}))},
 broadcast(event,payload){if(this.joined)this.sendRaw('realtime:room:'+this.roomCode,'broadcast',{type:'broadcast',event,payload},null)},
 onMessage(m){if(m.event==='phx_reply'&&m.topic==='phoenix'){this.ping=Math.round(performance.now()-this.lastPingAt);return}if(m.event==='phx_reply'&&m.payload?.status==='ok'&&!this.joined){this.joined=this.inRoom=true;this.reconnectUntil=Date.now()+30000;this.setStatus('Connected','online');this.track();this.openLobby();if(this.rejoiningPlaying){this.rejoiningPlaying=false;this.active=true;startGame(1,'multiplayer');toast('Reconnected to the active room')}return}if(m.event==='presence_state'){this.readPresence(m.payload);return}if(m.event==='presence_diff'){this.applyPresenceDiff(m.payload);return}if(m.event==='broadcast'){const e=m.payload?.event,p=m.payload?.payload;if(e)this.onBroadcast(e,p)}},
 track(){this.sendRaw('realtime:room:'+this.roomCode,'presence',{type:'presence',event:'track',payload:{id:this.uid(),name:save.profile.name,avatar:save.profile.avatar,ready:false,host:this.isHost,color:this.colors[this.players.size%3],online_at:Date.now()}})},
 readPresence(state){this.players.clear();for(const [id,v] of Object.entries(state||{})){const meta=(v.metas||v)[0]||v;this.players.set(id,{...meta,id})}this.ensureSelf();this.renderLobby()},
 applyPresenceDiff(diff){for(const [id,v] of Object.entries(diff.joins||{})){const meta=(v.metas||[])[0];if(meta)this.players.set(id,{...meta,id})}for(const id of Object.keys(diff.leaves||{}))this.players.delete(id);this.ensureSelf();this.renderLobby();if(this.active&&this.isHost)this.migrateHostIfNeeded()},
 ensureSelf(){if(!this.players.has(this.uid()))this.players.set(this.uid(),{id:this.uid(),name:save.profile.name,avatar:save.profile.avatar,ready:this.players.get(this.uid())?.ready||false,host:this.isHost,color:this.colors[0]})},
 onBroadcast(event,p){if(event==='lobby'){const old=this.players.get(p.id)||{};this.players.set(p.id,{...old,...p});this.renderLobby()}else if(event==='start'&&!this.active){this.active=true;this.isHost=p.hostId===this.uid();startGame(p.stage||1,'multiplayer')}else if(event==='player_state'&&p.id!==this.uid()){const old=this.remotePlayers.get(p.id)||{rx:p.x,ry:p.y};this.remotePlayers.set(p.id,{...old,...p,last:performance.now()});if(this.isHost)this.players.set(p.id,{...(this.players.get(p.id)||{}),...p})}else if(event==='world'&&!this.isHost)this.receiveWorld(p);else if(event==='ability'&&this.isHost)this.handleAbility(p);else if(event==='collect_gem'&&this.isHost){const g=gems.find(x=>x.netId===p.gemId);if(g){g.dead=true;this.broadcast('gem_taken',{gemId:p.gemId,playerId:p.id})}}else if(event==='gem_taken'){const g=gems.find(x=>x.netId===p.gemId);if(g)g.dead=true}else if(event==='damage_player'){if(p.id===this.uid())hurtPlayer(p.damage)}else if(event==='revive'){if(p.id===this.uid()){player.hp=Math.max(30,player.maxHp*.35);player.dead=false;player.invuln=2}}else if(event==='host'){this.isHost=p.id===this.uid();if(this.room)this.room.host_id=p.id;this.renderLobby();toast(this.isHost?'You are now the host':`${p.name} is now the host`)}else if(event==='admin_swarm'){tone(110,.7,'sawtooth',.15,260);toast('⚠ LIVE EVENT: Surprise Junk-Food Swarm!');if(this.isHost&&!G.swarm){G.swarmCycle=Math.floor(Math.random()*Object.keys(enemyDefs).length);startJunkSwarm()}}else if(event==='leave'){this.players.delete(p.id);this.remotePlayers.delete(p.id);this.renderLobby()}},
 migrateHostIfNeeded(){if(this.players.has(this.room?.host_id))return;const next=[...this.players.values()].sort((a,b)=>String(a.id).localeCompare(String(b.id)))[0];if(!next)return;this.room.host_id=next.id;this.isHost=next.id===this.uid();if(this.isHost)this.broadcast('host',{id:next.id,name:next.name})},
 openLobby(){document.querySelector('#mpLobby').classList.remove('hidden');document.querySelector('#mpRoomCode').textContent=this.roomCode;this.renderLobby()},
 renderLobby(){const box=document.querySelector('#mpPlayerList');if(!box)return;this.ensureSelf();box.innerHTML=[...this.players.values()].slice(0,3).map((p,i)=>`<div class="mp-player"><span class="avatar">${p.avatar||'🦸'}</span><b>${this.escape(p.name||'Player')}</b><span class="host">${p.host||p.id===this.room?.host_id?'👑 Host':''}</span><span class="${p.ready?'ready':''}">${p.ready?'✓ Ready':'Not Ready'}</span></div>`).join('');document.querySelector('#mpStart').classList.toggle('hidden',!this.isHost);document.querySelector('#mpStart').disabled=this.players.size<2||[...this.players.values()].some(p=>p.id!==this.uid()&&!p.ready);document.querySelector('#mpLobbyMessage').textContent=`${this.players.size}/3 connected · ${this.ping||'—'} ms`},
 toggleReady(){const me=this.players.get(this.uid());me.ready=!me.ready;document.querySelector('#mpReady').textContent=me.ready?'✓ Ready':'Not Ready';this.broadcast('lobby',me);this.renderLobby()},
 start(){if(!this.isHost||this.players.size<2)return;this.active=true;this.broadcast('start',{hostId:this.uid(),stage:1,seed:Date.now()});this.api(`multiplayer_rooms?id=eq.${this.room.id}`,{method:'PATCH',body:JSON.stringify({status:'playing',last_active:new Date().toISOString()})}).catch(()=>{});startGame(1,'multiplayer')},
 async leave(){if(!this.inRoom)return;this.broadcast('leave',{id:this.uid()});try{await this.api(`rpc/leave_multiplayer_room`,{method:'POST',body:JSON.stringify({p_room:this.room.id})})}catch{}this.closeSocket(false);this.reset();showScreen('menu')},
 closeSocket(reconnect=false){clearInterval(this.heartbeat);clearTimeout(this.reconnectTimer);if(this.socket){this.socket.onclose=null;this.socket.close()}this.socket=null;this.joined=false;if(!reconnect)this.reconnectUntil=0},
 reset(){this.active=this.inRoom=this.isHost=false;this.room=null;this.roomCode='';this.players.clear();this.remotePlayers.clear();document.querySelector('#mpLobby')?.classList.add('hidden');this.setStatus('Offline','offline')},
 tick(dt){if(!this.active)return;this.memberClock-=dt;if(this.memberClock<=0){this.memberClock=15;this.api(`multiplayer_members?room_id=eq.${this.room.id}&player_id=eq.${this.uid()}`,{method:'PATCH',body:JSON.stringify({last_seen:new Date().toISOString(),connected:true})}).catch(()=>{})}if(this.isHost){this.simulateRemoteCombat(dt);this.roomClock-=dt;if(this.roomClock<=0){this.roomClock=20;this.api(`multiplayer_rooms?id=eq.${this.room.id}`,{method:'PATCH',body:JSON.stringify({last_active:new Date().toISOString()})}).catch(()=>{})}}this.sendClock-=dt;this.snapshotClock-=dt;if(this.sendClock<=0){this.sendClock=1/15;this.broadcast('player_state',this.localState())}if(this.isHost&&this.snapshotClock<=0){this.snapshotClock=.1;this.broadcast('world',this.worldState())}this.interpolate(dt);if(!player.dead){for(const p of this.remotePlayers.values())if(!p.alive&&Math.hypot(p.rx-player.x,p.ry-player.y)<75){p.reviveProgress=(p.reviveProgress||0)+dt;if(p.reviveProgress>=3){p.reviveProgress=0;p.alive=true;this.broadcast('revive',{id:p.id,by:this.uid()});toast(`${p.name} revived!`)}}else p.reviveProgress=0}this.updateHUD()},
 localState(){return{id:this.uid(),name:save.profile.name,avatar:save.profile.avatar,color:this.players.get(this.uid())?.color||this.colors[0],x:+player.x.toFixed(1),y:+player.y.toFixed(1),vx:+(player.dir.x*player.speed).toFixed(1),vy:+(player.dir.y*player.speed).toFixed(1),dx:player.dir.x,dy:player.dir.y,hp:Math.ceil(player.hp),maxHp:player.maxHp,level:player.level,xp:Math.floor(player.xp),alive:player.hp>0,shield:player.invuln>1,weapons:Object.fromEntries(Object.entries(player.weapons).map(([k,v])=>[k,[v.level,!!v.evolved]])),passives:player.passives}},
 worldState(){const cx=player.x,cy=player.y,near=enemies.filter(e=>Math.abs(e.x-cx)<1500&&Math.abs(e.y-cy)<1000).slice(0,500);return{t:+G.time.toFixed(2),score:Math.floor(G.score),boss:G.boss?{id:'boss',x:+G.boss.x.toFixed(1),y:+G.boss.y.toFixed(1),hp:Math.ceil(G.boss.hp),maxHp:G.boss.maxHp,name:G.boss.name}:null,e:near.map((e,i)=>[e.netId||(e.netId='e'+Date.now().toString(36)+i),e.type,+e.x.toFixed(1),+e.y.toFixed(1),Math.ceil(e.hp),e.maxHp,e.state||0,!!e.elite]),g:gems.slice(0,250).map((g,i)=>[g.netId||(g.netId='g'+Date.now().toString(36)+i),+g.x.toFixed(1),+g.y.toFixed(1),g.v]),s:enemyShots.slice(0,250).map(p=>[+p.x.toFixed(1),+p.y.toFixed(1),+p.vx.toFixed(1),+p.vy.toFixed(1),p.r,p.life]),p:projectiles.slice(0,500).map(p=>[p.kind,+p.x.toFixed(1),+p.y.toFixed(1),+p.vx.toFixed(1),+p.vy.toFixed(1),p.r,+p.life.toFixed(2),p.length||0])}},
 receiveWorld(s){this.hostTime=s.t;G.time=s.t;G.score=s.score;const seen=new Set();for(const a of s.e||[]){seen.add(a[0]);let e=this.enemyTargets.get(a[0]);if(!e){e={netId:a[0],type:a[1],icon:enemyDefs[a[1]]?.icon||'🍔',x:a[2],y:a[3],rx:a[2],ry:a[3],r:enemyDefs[a[1]]?.size||20,hp:a[4],maxHp:a[5],state:a[6],elite:a[7],dead:false};this.enemyTargets.set(a[0],e)}e.rx=a[2];e.ry=a[3];e.hp=a[4];e.maxHp=a[5];e.state=a[6];e.elite=a[7]}for(const id of this.enemyTargets.keys())if(!seen.has(id))this.enemyTargets.delete(id);enemies=[...this.enemyTargets.values()];gems=(s.g||[]).map(a=>({netId:a[0],x:a[1],y:a[2],v:a[3],r:6}));enemyShots=(s.s||[]).map(a=>({x:a[0],y:a[1],vx:a[2],vy:a[3],r:a[4],life:a[5],dmg:0}));projectiles=(s.p||[]).map(a=>({kind:a[0],x:a[1],y:a[2],vx:a[3],vy:a[4],r:a[5],life:a[6],length:a[7],age:0,hit:new Set(),pierce:0}));if(s.boss&&G.boss){G.boss.hp=s.boss.hp;G.boss.maxHp=s.boss.maxHp}},
 interpolate(dt){const k=Math.min(1,dt*12);for(const e of this.enemyTargets.values()){e.x+=(e.rx-e.x)*k;e.y+=(e.ry-e.y)*k}for(const p of this.remotePlayers.values()){p.rx+=(p.x-p.rx)*k;p.ry+=(p.y-p.ry)*k}},
 simulateRemoteCombat(dt){for(const rp of this.remotePlayers.values()){if(!rp.alive||!rp.weapons)continue;rp.weaponCD=rp.weaponCD||{};const target=nearestFrom(rp.x,rp.y,850);if(!target)continue;const a=Math.atan2(target.y-rp.y,target.x-rp.x);for(const [id,data] of Object.entries(rp.weapons)){rp.weaponCD[id]=(rp.weaponCD[id]||0)-dt;if(rp.weaponCD[id]>0)continue;const lv=data[0],e=data[1],rate=e?.65:Math.max(.35,1.15-lv*.1);rp.weaponCD[id]=rate;const kind={orange:'orange',tomato:'tomato',corn:'corn',cucumber:'cucumber',smoothie:'smoothie',chakram:'chakram',leaf:'leaf',seed:'seed',fish:'fish',apple:'apple',water:'water',vitamin:'vitamin'}[id]||'carrot',count=e?3:1;for(let i=0;i<count;i++)shoot(rp.x,rp.y,a+(i-(count-1)/2)*.14,e?480:360,(14+lv*7)*(e?1.8:1),kind,e?2.5:1.8,{r:e?11:7,pierce:e?4:0,homing:id==='fish',returning:id==='apple'||id==='chakram',returnDelay:.7,explode:id==='tomato',blast:90})}}},
 handleAbility(p){/* Host validates requested dashes/abilities before rebroadcast. */if(p.type==='dash')this.broadcast('effect',{type:'dash',id:p.id,x:p.x,y:p.y})},
 updateHUD(){let box=document.querySelector('#teammateHud');if(!box){box=document.createElement('div');box.id='teammateHud';box.className='teammate-hud';document.querySelector('#app').appendChild(box)}box.innerHTML=[...this.remotePlayers.values()].map(p=>`<div class="teammate-card" style="--pc:${p.color}"><b>${p.avatar} ${this.escape(p.name)} · Lv.${p.level}</b><div class="mini-hp"><i style="width:${Math.max(0,p.hp/p.maxHp*100)}%"></i></div><small>${p.alive?'Alive':'Needs revival'} · ${this.ping||'—'}ms</small></div>`).join('')},
 escape(v){const d=document.createElement('div');d.textContent=String(v);return d.innerHTML},
 draw(ctx,worldToScreen,emoji){if(!this.active)return;for(const p of this.remotePlayers.values()){const q=worldToScreen(p.rx,p.ry);ctx.save();ctx.strokeStyle=p.color||'#fff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(q.x,q.y,23,0,Math.PI*2);ctx.stroke();emoji(p.avatar||'🦸',q.x,q.y,38,1);ctx.fillStyle='rgba(10,45,38,.85)';ctx.fillRect(q.x-35,q.y-39,70,13);ctx.fillStyle='#fff';ctx.font='900 10px sans-serif';ctx.textAlign='center';ctx.fillText(`${p.name} Lv.${p.level}`,q.x,q.y-29);ctx.restore()}},
 async copy(){await navigator.clipboard.writeText(this.roomCode);toast('Room code copied!')}
};
addEventListener('DOMContentLoaded',()=>{document.querySelector('#mpCreate').onclick=()=>MP.createRoom();document.querySelector('#mpJoin').onclick=()=>MP.joinByCode();document.querySelector('#mpCopy').onclick=()=>MP.copy();document.querySelector('#mpReady').onclick=()=>MP.toggleReady();document.querySelector('#mpStart').onclick=()=>MP.start();document.querySelector('#mpLeave').onclick=()=>MP.leave()});
addEventListener('beforeunload',()=>{if(MP.inRoom)MP.broadcast('leave',{id:MP.uid()})});
