/* Permanent Starter Weapon Roulette and dedicated in-run starter category.
   All BP, spins, inventory and administrator mutations are verified by Supabase. */
'use strict';
const Starter={
 cost:250,data:null,selected:null,pendingRun:null,spinning:false,skip:false,
 rarities:{Common:{color:'#aeb9b3'},Uncommon:{color:'#5bd873'},Rare:{color:'#4ca8ff'},Epic:{color:'#c56cff'},Legendary:{color:'#ffb52f'},Mythic:{color:'#ff547e'}},
 defs:{
  garlic:{name:'Garlic Nova',icon:'🧄',rarity:'Common',evolution:'Sacred Garlic Singularity',passive:'armor',desc:'Periodic close-range garlic shockwaves.'},
  chili:{name:'Chili Blaster',icon:'🌶️',rarity:'Common',evolution:'Inferno Chili Rail',passive:'attackSpeed',desc:'Alternating accelerating heat bolts.'},
  cabbage:{name:'Cabbage Crusher',icon:'🥬',rarity:'Uncommon',evolution:'Fortress Cabbage Ram',passive:'health',desc:'Heavy rolling cabbage that ricochets.'},
  onion:{name:'Onion Cyclone',icon:'🧅',rarity:'Uncommon',evolution:'Tearstorm Onion Cyclone',passive:'cooldown',desc:'Curving onion blades circle outward.'},
  potato:{name:'Potato Mortar',icon:'🥔',rarity:'Rare',evolution:'Loaded Potato Cataclysm',passive:'explosionRadius',desc:'High-arc delayed mortar explosions.'},
  eggplant:{name:'Eggplant Whip',icon:'🍆',rarity:'Rare',evolution:'Violet Eggplant Lash',passive:'crit',desc:'A sweeping penetrating energy lash.'},
  coconut:{name:'Coconut Cannon',icon:'🥥',rarity:'Epic',evolution:'Tidal Coconut Breaker',passive:'knockback',desc:'Massive decelerating knockback shells.'},
  pineapple:{name:'Pineapple Launcher',icon:'🍍',rarity:'Epic',evolution:'Royal Pineapple Minefield',passive:'count',desc:'Pineapple mines burst into radial spikes.'},
  peanut:{name:'Peanut Barrage',icon:'🥜',rarity:'Legendary',evolution:'Thunder Peanut Barrage',passive:'projectileSpeed',desc:'Rapid chained ricochet volleys.'},
  pepper:{name:'Pepper Storm',icon:'🫑',rarity:'Mythic',evolution:'Cosmic Pepper Apocalypse',passive:'bossDamage',desc:'Color-shifting homing pepper storm.'}
 },
 async call(body){return Online.call('starter-gacha',body)},
 async refresh(silent=false){if(!Online.enabled()||!save.profile){if(!silent)toast('Starter Roulette requires Supabase');return null}try{this.data=await this.call({action:'profile'});this.selected=this.data.profile.selected_starter||this.selected;this.renderAll();$('#progressionAdminButton').classList.toggle('hidden',!this.data.adminRole);return this.data}catch(e){this.data=null;if(!silent)toast(e.message||'Starter service unavailable');return null}},
 bp(){return this.data?.profile?.battle_points||0},inventory(){return this.data?.inventory||[]},owned(id){return this.inventory().find(x=>x.weapon_id===id)},
 renderAll(){const bp=this.bp();$('#bpCounter').textContent=`BP ${bp.toLocaleString()}`;$('#rouletteBP').textContent=`${bp.toLocaleString()} BP`;const free=!!this.data?.profile?.free_starter_spin;$('#rouletteSpin').textContent=free?'First Spin · FREE':`Spin · ${this.cost} BP`;$('#rouletteSpin').disabled=!free&&bp<this.cost;const g=this.data?.gacha||{};$('#pityStatus').innerHTML=`Rare+ in ≤ <b>${Math.max(1,10-(g.since_rare||0))}</b> · Epic+ in ≤ <b>${Math.max(1,30-(g.since_epic||0))}</b> · Legendary+ in ≤ <b>${Math.max(1,80-(g.since_legendary||0))}</b> · Mythic in ≤ <b>${Math.max(1,200-(g.since_mythic||0))}</b>`;$('#starterCollection').innerHTML=Object.entries(this.defs).map(([id,d])=>{const own=this.owned(id),r=this.rarities[d.rarity];return `<article class="starter-card ${own?'owned':'locked'}" style="--rarity:${r.color}"><span>${d.icon}</span><b>${d.name}</b><small>${d.rarity}</small><em>${own?'★'.repeat(own.star_rank)+'☆'.repeat(5-own.star_rank):'LOCKED'}</em></article>`}).join('');$('#adminStarterWeapon').innerHTML=Object.entries(this.defs).map(([id,d])=>`<option value="${id}">${d.rarity} · ${d.name}</option>`).join('')},
 async spin(){if(this.spinning)return;this.spinning=true;this.skip=false;$('#rouletteSpin').disabled=true;try{const result=await this.call({action:'spin'});const sequence=Array.from({length:24},()=>{const x=Object.values(this.defs)[Math.floor(Math.random()*10)];return `${x.icon} ${x.name}`});if(!this.skip){for(let i=0;i<sequence.length;i++){if(this.skip)break;$('#rouletteTrack').textContent=sequence[i];$('#rouletteTrack').style.transform=`scale(${1+(i%3)*.04})`;await new Promise(r=>setTimeout(r,35+i*6))}}this.showReveal(result);await this.refresh(true)}catch(e){toast(e.message)}finally{this.spinning=false;this.renderAll()}},
 showReveal(r){const d=this.defs[r.weaponId],style=this.rarities[r.rarity];$('#starterReveal').classList.remove('hidden');$('#revealRarity').textContent=r.rarity;$('#revealRarity').style.color=style.color;$('#revealIcon').textContent=d.icon;$('#revealName').textContent=d.name;$('#revealDuplicate').textContent=r.duplicate?`Duplicate copy! Star Rank increased to ${r.starRank}.`:'New exclusive starter weapon unlocked!';$('#revealStars').textContent='★'.repeat(r.starRank)+'☆'.repeat(5-r.starRank);sfx(r.rarity==='Mythic'||r.rarity==='Legendary'?'evolve':'level')},
 async requestRun(stage,mode){const onlineData=await this.refresh(true);if(!onlineData){toast('Starter service unavailable — starting with normal weapons');startGame(stage,mode);return}const inv=this.inventory();if(!inv.length){showScreen('roulette');toast('Use your free spin to unlock a starter weapon');return}this.pendingRun={stage,mode};this.renderSelection();$('#starterSelectModal').classList.remove('hidden')},
 async requestMultiplayer(){const onlineData=await this.refresh(true);if(!onlineData){toast('Starter service unavailable — continuing to Online Co-op');showScreen('multiplayer');return}if(!this.inventory().length){showScreen('roulette');toast('Use your free spin to unlock a starter weapon');return}this.pendingRun={lobby:true};this.renderSelection();$('#starterSelectModal').classList.remove('hidden')},
 renderSelection(){const grid=$('#starterSelectGrid');grid.innerHTML=this.inventory().map(item=>{const d=this.defs[item.weapon_id],r=this.rarities[d.rarity];return `<button class="starter-select-card ${this.selected===item.weapon_id?'selected':''}" data-starter="${item.weapon_id}" style="--rarity:${r.color}"><span>${d.icon}</span><b>${d.name}</b><small>${d.rarity} · ${'★'.repeat(item.star_rank)}${'☆'.repeat(5-item.star_rank)}</small><em>${d.desc}</em></button>`}).join('');grid.querySelectorAll('[data-starter]').forEach(b=>b.onclick=()=>this.choose(b.dataset.starter))},
 async choose(id){try{await this.call({action:'select',weaponId:id});this.selected=id;$('#starterSelectModal').classList.add('hidden');const p=this.pendingRun;this.pendingRun=null;if(p?.lobby)showScreen('multiplayer');else if(p)startGame(p.stage,p.mode)}catch(e){toast(e.message)}},
 attachToPlayer(){const own=this.owned(this.selected);if(!own||!player)return;player.starter={id:this.selected,level:1,xp:0,nextXp:20,evolved:false,cd:.2,star:own.star_rank||0};this.updateHUD()},
 gainXp(v){const s=player?.starter;if(!s)return;s.xp+=v;while(s.level<5&&s.xp>=s.nextXp){s.xp-=s.nextXp;s.level++;s.nextXp=Math.floor(s.nextXp*1.65+12);toast(`${this.defs[s.id].icon} ${this.defs[s.id].name} reached Lv.${s.level}`)}if(s.level>=5&&(player.passives[this.defs[s.id].passive]||0)>=3&&!s.evolved){s.evolved=true;G.evolution=1.1;sfx('evolve');toast(`⭐ ${this.defs[s.id].evolution} evolved!`)}this.updateHUD()},
 bonuses(s){return{damage:1+s.star*.01,attack:1+s.star*.01,speed:1+s.star*.01,crit:s.star*.01}},
 update(dt){const s=player?.starter;if(!s||player.dead)return;s.cd-=dt;if(s.cd>0)return;const d=this.defs[s.id],b=this.bonuses(s),target=nearest(s.evolved?1100:750);if(!target&&s.id!=='garlic'&&s.id!=='onion')return;const a=target?Math.atan2(target.y-player.y,target.x-player.x):0,lv=s.level,e=s.evolved,power=b.damage*(1+lv*.22);s.cd=({garlic:1.55,chili:.55,cabbage:1.7,onion:1.35,potato:2.15,eggplant:1.4,coconut:2.25,pineapple:2.45,peanut:.28,pepper:.75}[s.id]/b.attack)*(e?.72:1);
  if(s.id==='garlic')projectiles.push({x:player.x,y:player.y,vx:0,vy:0,r:20,dmg:24*power,kind:'starterPulse',life:.7,pierce:999,hit:new Set(),age:0,growth:e?650:400,maxR:e?330:190,knock:e?80:38,critBonus:b.crit});
  if(s.id==='chili')for(let i=0;i<(e?5:2);i++)shoot(player.x,player.y,a+(i-(e?2:.5))*.1,330*b.speed,18*power,'starterChili',2.2,{r:e?10:7,accel:e?500:270,pierce:e?5:1,trail:true,critBonus:b.crit});
  if(s.id==='cabbage')shoot(player.x,player.y,a,260*b.speed,42*power,'starterCabbage',3.2,{r:e?20:15,bounce:e?8:3,ricochet:e?4:1,knock:e?100:55,critBonus:b.crit});
  if(s.id==='onion')for(let i=0;i<(e?12:5+lv);i++)shoot(player.x,player.y,i/(e?12:5+lv)*TAU,230*b.speed,15*power,'starterOnion',2.6,{r:e?12:8,spiral:e?.16:.09,pierce:e?4:1,critBonus:b.crit});
  if(s.id==='potato')shoot(player.x,player.y,a,240*b.speed,58*power,'starterPotato',1.5,{r:e?18:13,gravity:400,explode:true,detonateOnEnd:true,blast:e?185:105,multiBlast:e,critBonus:b.crit});
  if(s.id==='eggplant')for(let i=0;i<(e?5:2);i++)shoot(player.x,player.y,a+(i-(e?2:.5))*.23,650*b.speed,32*power,'starterEggplant',.8,{r:e?14:9,pierce:e?999:5,knock:30,critBonus:.12+b.crit});
  if(s.id==='coconut')shoot(player.x,player.y,a,310*b.speed,76*power,'starterCoconut',3,{r:e?24:18,decel:.985,pierce:e?5:1,knock:e?150:90,critBonus:b.crit});
  if(s.id==='pineapple'){const x=target?.x||player.x,y=target?.y||player.y;traps.push({x,y,r:e?90:58,life:e?12:7,dmg:25*power,cd:0,slow:1.2,kind:'starterPineapple'});if(e)for(let i=0;i<10;i++)shoot(x,y,i/10*TAU,290,20*power,'starterPineapple',1.5,{pierce:2,r:8})}
  if(s.id==='peanut')for(let i=0;i<(e?7:3+Math.floor(lv/2));i++)shoot(player.x,player.y,a+rnd(-.18,.18),520*b.speed,19*power,'starterPeanut',2.2,{r:6,ricochet:e?8:3,pierce:1,critBonus:.08+b.crit});
  if(s.id==='pepper')for(let i=0;i<(e?12:5+lv);i++)shoot(player.x,player.y,a+rnd(-.5,.5),360*b.speed,28*power,'starterPepper',3,{r:e?13:9,homing:true,turn:e?9:5,pierce:e?3:1,trail:true,critBonus:.1+b.crit});
  weaponSfx(s.id==='pepper'?'vitamin':'seed',e);this.updateHUD()},
 updateHUD(){let el=$('#starterWeaponHud');if(!el){el=document.createElement('div');el.id='starterWeaponHud';$('#hud').appendChild(el)}const s=player?.starter;if(!s){el.innerHTML='';return}const d=this.defs[s.id];el.innerHTML=`<div class="dedicated-starter ${s.evolved?'evolved':''}"><span>${d.icon}</span><b>Starter Lv.${s.level}${s.evolved?' ★':''}</b><i style="width:${clamp(s.xp/s.nextXp*100,0,100)}%"></i></div>`},
 async claim(type,key,extra={}){try{const r=await this.call({action:'claim',type,claimKey:key,...extra});if(this.data){this.data.profile.battle_points=r.battlePoints;this.renderAll()}toast(`+${r.awarded} BP`)}catch(e){if(!String(e.message).includes('already'))console.warn(e.message)}},
 claimRun(){const key=`run:${G.runId}`;this.claim('run',key,{survival:Math.floor(G.time),bosses:G.bossesDefeated});const day=new Date().toISOString().slice(0,10);if(G.time>=300)this.claim('daily',`daily:${day}`,{survival:Math.floor(G.time)});const week=Math.floor(Date.now()/604800000);if(G.bossesDefeated>=3)this.claim('weekly',`weekly:${week}`,{bosses:G.bossesDefeated});if(player.level>=25)this.claim('achievement','achievement:level25',{level:player.level})},
 async adminList(){try{const d=await Online.call('admin-progression',{action:'list',search:$('#adminPlayerSearch').value.trim()});this.adminPlayers=d.players;$('#adminPlayerList').innerHTML=d.players.map(p=>`<option value="${p.id}">${p.avatar} ${p.player_name} · ${p.battle_points} BP${p.banned?' · BANNED':''}</option>`).join('');this.showAdminPlayer()}catch(e){toast(e.message)}},
 showAdminPlayer(){const id=$('#adminPlayerList').value,p=(this.adminPlayers||[]).find(x=>x.id===id);if(!p)return;$('#adminPlayerDetails').textContent=`${p.player_name} · ${p.battle_points} BP · ${p.total_games} games · ${p.total_kills} kills`},
 async adminAction(action){const target=$('#adminPlayerList').value;if(!target)return toast('Select a player');if(['reset_progression','ban','lock'].includes(action)&&!confirm(`Confirm ${action.replace('_',' ')}?`))return;try{await Online.call('admin-progression',{action,targetId:target,amount:+$('#adminBPAmount').value,weaponId:$('#adminStarterWeapon').value,star:+$('#adminStarRank').value});toast('Administrator action completed');this.adminList()}catch(e){toast(e.message)}},
 init(){if(!$('#rouletteSpin'))return;$('#rouletteSpin').onclick=()=>this.spin();$('#rouletteSkip').onclick=()=>{this.skip=true};$('#revealClose').onclick=()=>$('#starterReveal').classList.add('hidden');$('#starterSelectCancel').onclick=()=>{$('#starterSelectModal').classList.add('hidden');this.pendingRun=null};$('#adminSearchButton').onclick=()=>this.adminList();$('#adminPlayerList').onchange=()=>this.showAdminPlayer();$$('[data-admin-action]').forEach(b=>b.onclick=()=>this.adminAction(b.dataset.adminAction));this.refresh(true)}
};
addEventListener('DOMContentLoaded',()=>Starter.init());
