import { cors,json,context } from '../_shared/common.ts';
const validWeapons=['garlic','chili','cabbage','onion','potato','eggplant','coconut','pineapple','peanut','pepper'];
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const {user,admin}=await context(req),b=await req.json(),action=String(b.action||'list');const {data:role}=await admin.from('progression_admins').select('role').eq('user_id',user.id).maybeSingle();if(!role)return json({error:'Progression administrator required'},403);
 if(action==='list'){const search=String(b.search||'').trim();let q=admin.from('profiles').select('id,player_name,avatar,battle_points,selected_starter,banned,total_games,total_play_time,total_kills').order('updated_at',{ascending:false}).limit(50);if(search)q=q.ilike('player_name',`%${search.slice(0,20)}%`);const {data,error}=await q;if(error)throw error;return json({players:data})}
 const target=String(b.targetId||'');if(!target)return json({error:'Select a player'},400);let details:any={};
 if(['add_bp','remove_bp','set_bp','reset_bp'].includes(action)){const {data:p}=await admin.from('profiles').select('battle_points').eq('id',target).single();let bp=p.battle_points;if(action==='add_bp')bp+=Math.max(0,Math.floor(Number(b.amount)||0));if(action==='remove_bp')bp=Math.max(0,bp-Math.max(0,Math.floor(Number(b.amount)||0)));if(action==='set_bp')bp=Math.max(0,Math.floor(Number(b.amount)||0));if(action==='reset_bp')bp=0;await admin.from('profiles').update({battle_points:bp}).eq('id',target);details={bp}}
 else if(['unlock','lock','star','grant_mythic'].includes(action)){const weapon=action==='grant_mythic'?'pepper':String(b.weaponId||'');if(!validWeapons.includes(weapon))return json({error:'Invalid weapon'},400);if(action==='lock')await admin.from('starter_inventory').delete().eq('user_id',target).eq('weapon_id',weapon);else{const star=action==='star'?Math.max(0,Math.min(5,Math.floor(Number(b.star)||0))):0;await admin.from('starter_inventory').upsert({user_id:target,weapon_id:weapon,copies:star+1,star_rank:star,updated_at:new Date().toISOString()});details={weapon,star}}}
 else if(action==='ban'||action==='unban'){await admin.from('profiles').update({banned:action==='ban'}).eq('id',target);details={banned:action==='ban'}}
 else if(action==='reset_progression'){await admin.from('starter_inventory').delete().eq('user_id',target);await admin.from('gacha_state').delete().eq('user_id',target);await admin.from('profiles').update({battle_points:0,selected_starter:null,free_starter_spin:true}).eq('id',target)}
 else return json({error:'Unknown admin action'},400);
 await admin.from('progression_admin_log').insert({admin_id:user.id,target_id:target,action,details});return json({success:true,...details})
 }catch(e){return json({error:e.message||'Admin request failed'},e.message==='Unauthorized'?401:400)}});
